import { jsPDF } from 'jspdf';
import { Scenario } from '@/store/useProjectStore';

export const generatePDFReport = async (
    scenarioA: Scenario,
    scenarioB?: Scenario,
    imageA?: string,
    imageB?: string
): Promise<void> => {
    if (!scenarioA.result) return;

    const doc = new jsPDF();
    const { kpis: kA } = scenarioA.result;
    const kB = scenarioB?.result?.kpis;

    // Header
    doc.setFillColor(15, 23, 42); // Navy
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text('HVAC AI 3D CFD REPORT', 20, 20);
    doc.setFontSize(10);
    doc.text(`Vertical AI Presales technical Validation - v2.0`, 20, 28);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 140, 28);

    // 1. Executive Summary
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(16);
    doc.text('1. Executive Design Summary', 20, 50);

    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Primary Scenario: ${scenarioA.name}`, 20, 58);
    if (scenarioB) doc.text(`Comparison Scenario: ${scenarioB.name}`, 110, 58);

    // 2. 3D Visual Results
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.text('2. 3D Simulation Visualization', 20, 75);

    if (imageA) {
        if (scenarioB && imageB) {
            // Side-by-side
            doc.addImage(imageA, 'PNG', 15, 80, 85, 55);
            doc.addImage(imageB, 'PNG', 110, 80, 85, 55);
            doc.setFontSize(8);
            doc.text(`${scenarioA.name}`, 15, 138);
            doc.text(`${scenarioB.name}`, 110, 138);
        } else {
            // Full width
            doc.addImage(imageA, 'PNG', 45, 80, 120, 75);
            doc.setFontSize(8);
            doc.text(`${scenarioA.name}`, 45, 158);
        }
    }

    // 3. Performance Overview (Side-by-Side Table)
    let y = scenarioB ? 150 : 170;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.text('3. Performance Comparison Matrix', 20, y);
    y += 10;

    const kpiRows = [
        ['Metric', 'Scenario A', scenarioB ? 'Scenario B' : 'Status', scenarioB ? 'Delta' : ''],
        ['Avg Temp', `${kA.avgTemp}°C`, kB ? `${kB.avgTemp}°C` : 'Validated', kB ? `${(kA.avgTemp - kB.avgTemp).toFixed(1)}K` : ''],
        ['Max Temp', `${kA.maxTemp}°C`, kB ? `${kB.maxTemp}°C` : 'Validated', kB ? `${(kA.maxTemp - kB.maxTemp).toFixed(1)}K` : ''],
        ['Min Temp', `${kA.minTemp}°C`, kB ? `${kB.minTemp}°C` : 'Validated', kB ? `${(kA.minTemp - kB.minTemp).toFixed(1)}K` : ''],
        ['Comfort Score', `${kA.comfortScore}/100`, kB ? `${kB.comfortScore}/100` : 'Target > 80', kB ? `${kA.comfortScore - kB.comfortScore}` : ''],
        ['PMV Index', `${kA.pmv}`, kB ? `${kB.pmv}` : 'Target ±0.5', kB ? `${(kA.pmv - kB.pmv).toFixed(2)}` : ''],
        ['CO2 (Proxy)', `${kA.co2Proxy} ppm`, kB ? `${kB.co2Proxy} ppm` : 'Target < 1000', kB ? `${kA.co2Proxy - kB.co2Proxy}` : ''],
    ];

    kpiRows.forEach((row, i) => {
        if (i === 0) {
            doc.setFillColor(248, 250, 252);
            doc.rect(20, y - 5, 175, 8, 'F');
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(9);
        } else {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
        }

        doc.text(row[0], 25, y);
        doc.text(row[1], 80, y);
        doc.text(row[2], 120, y);
        if (scenarioB) doc.text(row[3], 160, y);

        doc.setDrawColor(241, 245, 249);
        doc.line(20, y + 2, 195, y + 2);
        y += 8;
    });

    // 4. Geometry Delta
    y += 10;
    doc.setFontSize(14);
    doc.text('4. Design Parameters', 20, y);
    y += 10;

    const designRows = [
        ['Parameter', 'Scenario A', scenarioB ? 'Scenario B' : 'Unit'],
        ['Dimensions', `${scenarioA.geometry.length}x${scenarioA.geometry.width}m`, scenarioB ? `${scenarioB.geometry.length}x${scenarioB.geometry.width}m` : 'm'],
        ['Height', `${scenarioA.geometry.height}m`, scenarioB ? `${scenarioB.geometry.height}m` : 'm'],
        ['Supply Temp', `${scenarioA.boundaryParams.supplyTemp}°C`, scenarioB ? `${scenarioB.boundaryParams.supplyTemp}°C` : 'deg C'],
        ['Airflow', `${scenarioA.boundaryParams.airflowRate}m3/h`, scenarioB ? `${scenarioB.boundaryParams.airflowRate}m3/h` : 'm3/h'],
    ];

    designRows.forEach((row, i) => {
        doc.text(row[0], 25, y);
        doc.text(row[1], 80, y);
        doc.text(row[2], 120, y);
        y += 7;
    });

    // Disclaimer
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    const disclaimer = [
        'TECHNICAL DISCLAIMER: The results presented in this report are generated by an AI surrogate model trained on CFD datasets.',
        'This tool is intended for presales decision acceleration and technical consultation. It does not replace detailed',
        'engineering-grade CFD simulation for final physical system commissioning.'
    ];

    doc.text(disclaimer[0], 20, 275);
    doc.text(disclaimer[1], 20, 278);
    doc.text(disclaimer[2], 20, 281);

    const fileName = scenarioB
        ? `Comparison_Report_${scenarioA.name}_vs_${scenarioB.name}.pdf`
        : `Technical_Report_${scenarioA.name}.pdf`;

    doc.save(fileName.replace(/\s+/g, '_'));
};
